#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

# Project 1B
# Adding system calls STEP 5 
# Its for the user side Access
# below are the entries of the system calls we are creating.
# adding it here in pearl script automatically generates the assemply code needed for the user programs to invoke these system calls.
# makes them accessible to the user programs.
entry("getppid");
entry("ps");
entry("getschedhistory");

# Project 1C
entry("startMLFQ");
entry("stopMLFQ");
entry("getMLFQInfo");
